apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: wes-app-meta-cache-config
    files:
      - redis-config.conf
resources:
  - service.yaml
  - statefulset.yaml
