# Runs one instance of dcgm-exporter on every node (DaemonSet) and expose
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dcgm-exporter
  labels:
    app.kubernetes.io/name: dcgm-exporter
    app.kubernetes.io/version: 3.0.4-3.0.0-ubuntu20.04
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dcgm-exporter
      app.kubernetes.io/version: 3.0.4-3.0.0-ubuntu20.04
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dcgm-exporter
        app.kubernetes.io/version: 3.0.4-3.0.0-ubuntu20.04
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9400"
    spec:
      nodeSelector:
        kubernetes.io/arch: "amd64"
        resource.gpu: "true"
      priorityClassName: wes-high-priority
      containers:
        - securityContext:
            capabilities:
              add:
                - SYS_ADMIN
          image: nvcr.io/nvidia/k8s/dcgm-exporter:3.0.4-3.0.0-ubuntu20.04
          imagePullPolicy: IfNotPresent
          name: dcgm-exporter
          env:
            - name: DCGM_EXPORTER_KUBERNETES
              value: "true"
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
            requests:
              cpu: 50m
              memory: 50Mi
          ports:
            - name: http
              containerPort: 9400
              hostPort: 9400
          volumeMounts:
            - name: "pod-gpu-resources"
              readOnly: true
              mountPath: "/var/lib/kubelet/pod-resources"
      volumes:
        - name: "pod-gpu-resources"
          hostPath:
            path: "/var/lib/kubelet/pod-resources"
