apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-upload-agent
  labels:
    app.kubernetes.io/name: node-upload-agent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: node-upload-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node-upload-agent
    spec:
      containers:
      - image: waggle/node-upload-agent
        name: node-upload-agent
        resources:
          limits:
            cpu: 200m
            memory: 20Mi
          requests:
            cpu: 100m
            memory: 10Mi
        env:
        - name: SSH_CA_PUBKEY
          value: "/etc/ca/ca.pub"
        - name: SSH_HOST_KEY
          value: "/etc/waggle/ssh-host-key"
        - name: SSH_HOST_CERT
          value: "/etc/waggle/ssh-host-key-cert.pub"
        envFrom:
          - configMapRef:
              name: waggle-config
        volumeMounts:
        - name: ssh-ca-key
          mountPath: /etc/ca
          readOnly: true
        - name: ssh-upload-key
          mountPath: /etc/waggle
          readOnly: true
        - name: uploads
          mountPath: /uploads
        livenessProbe:
          exec:
            command:
            - rm
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 300
      volumes:
      - name: ssh-ca-key
        configMap:
          name: beehive-ssh-ca
      - name: ssh-upload-key
        secret:
          secretName: wes-beehive-upload-ssh-key
          defaultMode: 0600
      - name: uploads
        hostPath:
          path: /media/plugin-data/uploads
          type: DirectoryOrCreate
