apiVersion: v1
kind: Service
metadata:
  name: wes-rabbitmq
spec:
  selector:
    app: wes-rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
    - name: rabbitmq-management
      protocol: TCP
      port: 15672
    - name: mqtt
      protocol: TCP
      port: 1883
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wes-rabbitmq
spec:
  serviceName: wes-rabbitmq
  selector:
    matchLabels:
      app: wes-rabbitmq
  template:
    metadata:
      labels:
        app: wes-rabbitmq
    spec:
      priorityClassName: wes-high-priority
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      containers:
        - name: wes-rabbitmq
          image: rabbitmq:3.11.5-management-alpine
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi
          ports:
            - containerPort: 5672
            - containerPort: 15672
            - containerPort: 1883
          volumeMounts:
            - name: config
              mountPath: /etc/rabbitmq
              readOnly: true
            - name: data
              mountPath: /var/lib/rabbitmq
          readinessProbe:
            timeoutSeconds: 10
            exec:
              command: ["rabbitmq-diagnostics", "ping"]
          livenessProbe:
            timeoutSeconds: 10
            periodSeconds: 60
            exec:
              command: ["rabbitmq-diagnostics", "-q", "ping"]
      volumes:
        - name: config
          secret:
            secretName: wes-rabbitmq-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi
