---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wes-camera-provisioner-svc-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wes-camera-provisioner
  namespace: default
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["configmaps"]
    verbs: ["create", "get", "watch", "list", "update", "patch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wes-camera-provisioner
roleRef:
  kind: ClusterRole
  name: wes-camera-provisioner
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: wes-camera-provisioner-svc-account
    namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wes-camera-provisioner-ssh
data:
  config: |            
    Host github.com
            StrictHostKeyChecking no
            Hostname ssh.github.com
            IdentityFile /keys/hanwha_client_key
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: wes-camera-provisioner
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 1800
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            node-role.kubernetes.io/master: "true"
          restartPolicy: Never
          serviceAccountName: wes-camera-provisioner-svc-account
          priorityClassName: wes-high-priority
          hostNetwork: true
          containers:
          - name: wes-camera-provisioner
            image: waggle/wes-camera-provisioner:0.0.9
            resources:
              limits:
                memory: 100Mi
              requests:
                cpu: 200m
                memory: 100Mi
            env:
            - name: WAGGLE_CAMERA_ADMIN
              valueFrom:
                secretKeyRef:
                  name: wes-hanwha-camera-account-secret
                  key: username
            - name: WAGGLE_CAMERA_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wes-hanwha-camera-account-secret
                  key: password
            - name: WAGGLE_CAMERA_USER
              valueFrom:
                secretKeyRef:
                  name: wes-hanwha-camera-user-account-secret
                  key: username
            - name: WAGGLE_CAMERA_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wes-hanwha-camera-user-account-secret
                  key: password
            - name: WAGGLE_SWITCH_USER
              valueFrom:
                secretKeyRef:
                  name: wes-networkswitch-account-secret
                  key: username
            - name: WAGGLE_SWITCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wes-networkswitch-account-secret
                  key: password
            volumeMounts:
            - mountPath: /keys
              name: hanwha-client-ssh-key
              readOnly: true
            - mountPath: /etc/waggle
              name: waggle-node-manifest
              readOnly: true
            - mountPath: /root/.ssh
              name: hanwha-client-ssh-config
              readOnly: true
            - mountPath: /data
              name: data
          volumes:
          - name: hanwha-client-ssh-key
            secret:
              secretName: wes-camera-provisioner-ssh-key
              defaultMode: 0600
          - name: waggle-node-manifest
            configMap:
              name: waggle-node-manifest
          - name: hanwha-client-ssh-config
            configMap:
              name: wes-camera-provisioner-ssh
          - name: data
            persistentVolumeClaim:
              claimName: wes-camera-provisioner-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wes-camera-provisioner-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: local-path