apiVersion: apps/v1
kind: Deployment
metadata:
  name: wes-data-sharing-service
spec:
  selector:
    matchLabels:
      app: wes-data-sharing-service
  template:
    metadata:
      labels:
        app: wes-data-sharing-service
    spec:
      priorityClassName: wes-high-priority
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      containers:
        - name: wes-data-sharing-service
          image: waggle/wes-data-sharing-service:pr-16@sha256:7ca7bd0200115d013847c9b444395deb9038689db37980301dbae2c5e7a7ff0b
          resources:
            requests:
              cpu: 200m
              memory: 50Mi
            limits:
              memory: 50Mi
          envFrom:
            - configMapRef:
                name: wes-identity
          env:
            - name: RABBITMQ_HOST
              value: "wes-rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: service
            - name: RABBITMQ_PASSWORD
              value: service
            - name: SYSTEM_USERS
              value: service
