apiVersion: apps/v1
kind: Deployment
metadata:
  name: wes-data-sharing-service
spec:
  selector:
    matchLabels:
      app: wes-data-sharing-service
  template:
    metadata:
      labels:
        app: wes-data-sharing-service
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      containers:
      - name: wes-data-sharing-service
        image: waggle/wes-data-sharing-service:0.0.5
        envFrom:
        - configMapRef:
            name: waggle-config
        env:
        - name: RABBITMQ_HOST
          value: "wes-rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: wes-rabbitmq-service-account-secret
              key: username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wes-rabbitmq-service-account-secret
              key: password
        resources:
          limits:
            cpu: 200m
            memory: 20Mi
          requests:
            cpu: 100m
            memory: 10Mi

