apiVersion: v1
kind: Service
metadata:
  name: wes-scoreboard
spec:
  ports:
    - name: wes-scoreboard
      port: 6379
      targetPort: redis
  selector:
    app: wes-scoreboard
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wes-scoreboard
spec:
  selector:
    matchLabels:
      app: wes-scoreboard
  template:
    metadata:
      labels:
        app: wes-scoreboard
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      priorityClassName: wes-high-priority
      containers:
        - image: redis:7.0.4
          imagePullPolicy: IfNotPresent
          name: wes-scoreboard
          resources:
            limits:
              memory: 150Mi
            requests:
              cpu: 50m
              memory: 150Mi
          ports:
          - containerPort: 6379
            name: redis
