# The wes-plugin-network-policy-default-deny network policy ensures that
# pods are "isolated" by default and require adding network permissions.
#
# See these examples:
# https://kubernetes.io/docs/concepts/services-networking/network-policies/#default-deny-all-ingress-traffic
# https://kubernetes.io/docs/concepts/services-networking/network-policies/#default-deny-all-egress-traffic
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wes-plugin-network-policy-dns
spec:
  podSelector:
    matchLabels:
      role: plugin
  policyTypes:
  - Egress
  egress:
  - ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wes-plugin-network-policy-rabbitmq
spec:
  podSelector:
    matchLabels:
      role: plugin
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: wes-rabbitmq
    ports:
    - protocol: TCP
      port: 5672
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wes-plugin-network-policy-audio-server
spec:
  podSelector:
    matchLabels:
      role: plugin
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: wes-audio-server
    ports:
    - protocol: TCP
      port: 4713
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wes-plugin-network-policy-playback-server
spec:
  podSelector:
    matchLabels:
      role: plugin
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: wes-playback-server
    ports:
    - protocol: TCP
      port: 8090
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wes-plugin-network-policy-gps-server
spec:
  podSelector:
    matchLabels:
      role: plugin
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: wes-gps-server
    ports:
    - protocol: TCP
      port: 2947