apiVersion: v1
kind: Service
metadata:
  name: wes-audio-server
spec:
  selector:
    app: wes-audio-server
  ports:
    - name: pulseaudio
      protocol: TCP
      port: 4713
      targetPort: 4713
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wes-audio-server
spec:
  selector:
    matchLabels:
      app: wes-audio-server
  template:
    metadata:
      labels:
        app: wes-audio-server
    spec:
      containers:
      - image: waggle/wes-audio-server:0.1.0
        name: wes-audio-server
        ports:
        - containerPort: 4713
# TODO(sean) use device plugin to run on all devices with microphones
