# TODO: rename to collector
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wes-lorawan-gateway
spec:
  selector:
    matchLabels:
      app: wes-lorawan-gateway
  template:
    metadata:
      labels:
        app: wes-lorawan-gateway
    spec:
      priorityClassName: wes-high-priority
      nodeSelector:
        resource.lorawan: "true"
      containers:
        - name: wes-lorawan-gateway
          image: rakwireless/udp-packet-forwarder:v1.1.3
          # Need this to get access to write so /sys (gpio)
          securityContext:
            privileged: true
          resources:
            # TODO: analyze resource usage
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 100m
              memory: 25Mi
          envFrom:
            - configMapRef:
                name: wes-identity
          env:
            - name: MODEL
              value: "RAK7248"
            - name: BAND
              value: "US_902_928"
            - name: GATEWAY_EUI
              value: "D2CE19FFFEC9D449"
            - name: SERVER_HOST
              value: "wes-chirpstack-gateway-bridge"
            - name: SERVER_PORT
              value: "1700"
          volumeMounts:
            - name: sys
              mountPath: /sys
              mountPropagation: HostToContainer
              readOnly: false
          # TODO: liveness probe to ensure its working
      volumes:
        - name: sys
          hostPath:
            path: /sys
