apiVersion: v1
kind: Service
metadata:
  name: wes-plugin-scheduler
spec:
  ports:
    - name: wes-plugin-scheduler
      port: 8080
      targetPort: 8080
  selector:
    app: wes-plugin-scheduler
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wes-plugin-scheduler
spec:
  selector:
    matchLabels:
      app: wes-plugin-scheduler
  template:
    metadata:
      labels:
        app: wes-plugin-scheduler
        sagecontinuum.org/plugin-task: scheduler
    spec:
      priorityClassName: wes-high-priority
      serviceAccountName: wes-plugin-scheduler
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      containers:
        - image: waggle/edge-scheduler:0.22.4
          imagePullPolicy: IfNotPresent
          name: wes-plugin-scheduler
          command: ["nodescheduler"]
          args:
            - -in-cluster
            - -policy
            - gpuaware
            - -nodename
            - "$(WAGGLE_NODE_VSN)"
            - -goalstream-url
            - "https://es.sagecontinuum.org/api/v1/goals/$(WAGGLE_NODE_VSN)/stream"
          envFrom:
            - configMapRef:
                name: wes-identity
          env:
            - name: WAGGLE_APP_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          resources:
            limits:
              memory: 150Mi
            requests:
              cpu: 100m
              memory: 150Mi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wes-plugin-scheduler
  namespace: default
rules:
  - apiGroups: ["", "batch"] # "" indicates the core API group
    resources:
      [
        "namespaces",
        "configmaps",
        "services",
        "jobs",
        "nodes",
        "pods",
        "pods/log",
      ]
    verbs: ["create", "get", "watch", "list", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wes-plugin-scheduler-view
  namespace: default
roleRef:
  kind: ClusterRole
  name: wes-plugin-scheduler
  apiGroup: rbac.authorization.k8s.io
  # `edit` is a built-in cluster role. more info about these can be found here:
  # https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles
subjects:
  - kind: ServiceAccount
    name: wes-plugin-scheduler
    namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wes-plugin-scheduler
