apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wes-upload-agent
  labels:
    app.kubernetes.io/name: wes-upload-agent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: wes-upload-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wes-upload-agent
    spec:
      priorityClassName: wes-high-priority
      containers:
        - image: waggle/wes-upload-agent:0.1.2
          name: wes-upload-agent
          resources:
            limits:
              cpu: 200m
              memory: 20Mi
            requests:
              cpu: 100m
              memory: 10Mi
          envFrom:
            - configMapRef:
                name: wes-identity
            - configMapRef:
                name: wes-upload-agent-env
          volumeMounts:
            - name: config
              mountPath: /etc/upload-agent
              readOnly: true
            - name: uploads
              mountPath: /uploads
          livenessProbe:
            exec:
              command:
                - rm
                - /tmp/healthy
            # check every minute and allow up to 1h worth of fails in case of a long transfer
            periodSeconds: 60
            failureThreshold: 60
      volumes:
        - name: config
          secret:
            secretName: wes-upload-agent-config
            defaultMode: 0600
        - name: uploads
          hostPath:
            path: /media/plugin-data/uploads
            type: DirectoryOrCreate
