apiVersion: v1
kind: LimitRange
metadata:
  name: wes-default-limits
spec:
  limits:
    - default:
        memory: 1Gi
      defaultRequest:
        cpu: 500m
        memory: 1Gi
      type: Container
