apiVersion: v1
kind: Service
metadata:
  name: wes-playback-server
spec:
  selector:
    app: wes-playback-server
  ports:
    - name: stream
      protocol: TCP
      port: 8090
      targetPort: 8090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wes-playback-server
spec:
  priorityClassName: wes-high-priority
  selector:
    matchLabels:
      app: wes-playback-server
  template:
    metadata:
      labels:
        app: wes-playback-server
    spec:
      containers:
        - image: waggle/wes-playback-server:0.1.0
          imagePullPolicy: IfNotPresent
          name: wes-playback-server
          ports:
            - containerPort: 8090
