apiVersion: v1
kind: Service
metadata:
  name: wes-rabbitmq
spec:
  selector:
    app: wes-rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
    - name: rabbitmq-management
      protocol: TCP
      port: 15672
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wes-rabbitmq
spec:
  serviceName: wes-rabbitmq
  selector:
    matchLabels:
      app: wes-rabbitmq
  template:
    metadata:
      labels:
        app: wes-rabbitmq
    spec:
      priorityClassName: wes-high-priority
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      containers:
        - name: wes-rabbitmq
          image: rabbitmq:3.8.11-management-alpine
          ports:
            - containerPort: 5672
            - containerPort: 15672
          volumeMounts:
            - name: config
              mountPath: /etc/rabbitmq
              readOnly: true
            - name: data
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: config
          secret:
            secretName: wes-rabbitmq-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
