apiVersion: v1
kind: Service
metadata:
  name: wes-sciencerule-checker
spec:
  ports:
    - name: api
      port: 5000
      targetPort: api
      protocol: TCP
    - name: metrics
      port: 8000
      targetPort: metrics
      protocol: TCP
  selector:
    app: wes-sciencerule-checker
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wes-sciencerule-checker
spec:
  selector:
    matchLabels:
      app: wes-sciencerule-checker
  template:
    metadata:
      labels:
        app: wes-sciencerule-checker
    spec:
      priorityClassName: wes-high-priority
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      containers:
        - image: waggle/sciencerule-checker:0.0.7
          imagePullPolicy: IfNotPresent
          name: wes-sciencerule-checker
          env:
            - name: NODE_INFLUXDB_URL
              value: "http://wes-node-influxdb:8086"
            - name: NODE_INFLUXDB_QUERY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: wes-node-influxdb-waggle-token
                  key: token
          ports:
            - name: api
              containerPort: 5000
            - name: metrics
              containerPort: 8000
          resources:
            limits:
              memory: 150Mi
            requests:
              cpu: 100m
              memory: 150Mi
