[logging]
level="debug"

[postgresql]
dsn="postgres://$POSTGRESQL_USER:$POSTGRESQL_PWD@$POSTGRESQL_HOST/$POSTGRESQL_DB?sslmode=disable"

[redis]
servers=["redis://$REDIS_HOST/"]

[network]
net_id="000000"
enabled_regions=["us915_sb2"]
# Custom ADR plugins.
#
# The custom ADR plugin must be implemented in JavaScript. For an example
# skeleton, please see:
# https://github.com/chirpstack/chirpstack/blob/master/examples/adr_plugins/plugin_skeleton.js
adr_plugins=["/etc/chirpstack-waggle/no_adr.js",
             "/etc/chirpstack-waggle/dr_0.js",
             "/etc/chirpstack-waggle/dr_1.js",
             "/etc/chirpstack-waggle/dr_2.js",
             "/etc/chirpstack-waggle/dr_3.js"]

[api]
bind="0.0.0.0:$WEB_API_PORT"
secret="sPQT3pZfR191Y9lJP9CreqbThIvjGlR8YYMNmav9hkI="

[monitoring]
# /health  - Returns 200 in case the healthchecks have passed.
# /metrics - Returns metrics which can be scraped by Prometheus.
bind="0.0.0.0:$METRICS_PORT"

[integration]
enabled = ["mqtt"]

[integration.mqtt]
server="tcp://$MQTT_BROKER_HOST:$MQTT_BROKER_PORT/"
json=true
username="$MQTT_BROKER_USER"
password="$MQTT_BROKER_PASSWORD"
client_id="wes-chirpstack-server"
