apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - wes-chirpstack-gateway-service.yaml
  - wes-chirpstack-gateway-deployment.yaml
  - wes-chirpstack-server-service.yaml
  - wes-chirpstack-server-deployment.yaml
  - wes-chirpstack-redis-service.yaml
  - wes-chirpstack-redis-deployment.yaml
  - wes-chirpstack-redis-volume.yaml
  - wes-chirpstack-postgresql-service.yaml
  - wes-chirpstack-postgresql-deployment.yaml
  - wes-chirpstack-postgresql-volume.yaml
  - wes-chirpstack-postgresql-configmap.yaml

configMapGenerator:
  - name: chirpstack-gateway-bridge-config-cm
    files:
      - chirpstack-gateway-bridge.toml
  - name: chirpstack-server-config-cm
    files:
      - chirpstack.toml
      - region_us915.toml
