apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wes-chirpstack-postgresql-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi
