apiVersion: apps/v1
kind: Deployment
metadata:
  name: wes-chirpstack-server
spec:
  selector:
    matchLabels:
      app: wes-chirpstack-server
  template:
    metadata:
      labels:
        app: wes-chirpstack-server
    spec:
      priorityClassName: wes-high-priority
      containers:
        - name: wes-chirpstack-server
          image: waggle/wes-chirpstack-server:0.2.0
          imagePullPolicy: IfNotPresent
          command: ["chirpstack"]
          args: ["-c", "/etc/chirpstack-waggle"]
          lifecycle:
            # import the lorawan ttn devices profile templates
            postStart:
              exec:
                command:
                  [
                    "chirpstack",
                    "-c",
                    "/etc/chirpstack-waggle",
                    "import-legacy-lorawan-devices-repository",
                    "-d",
                    "/opt/lorawan-devices",
                  ]
          ports:
            - containerPort: 8080
            - name: metrics
              containerPort: 9100
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              memory: 100Mi
          envFrom:
            - configMapRef:
                name: wes-identity
          env:
            - name: POSTGRESQL_HOST
              value: "wes-chirpstack-postgresql"
            - name: POSTGRESQL_USER
              value: "chirpstack"
            - name: POSTGRESQL_PWD
              value: "chirpstack"
            - name: POSTGRESQL_DB
              value: "chirpstack"
            - name: REDIS_HOST
              value: "wes-chirpstack-redis:6379"
            - name: MQTT_BROKER_HOST
              value: "wes-rabbitmq"
            - name: MQTT_BROKER_PORT
              value: "1883"
            - name: MQTT_BROKER_USER
              value: "service"
            - name: MQTT_BROKER_PASSWORD
              value: "service"
            - name: WEB_API_PORT
              value: "8080"
            - name: METRICS_PORT
              value: "9100"
          volumeMounts:
            - name: server-config-volume
              mountPath: /etc/chirpstack-waggle
              readOnly: true
          startupProbe:
            httpGet:
              path: /health
              port: metrics
            initialDelaySeconds: 5
            timeoutSeconds: 10
            failureThreshold: 10
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /health
              port: metrics
            timeoutSeconds: 10
            failureThreshold: 3
            periodSeconds: 60
        - name: chirpstack-rest-api
          image: chirpstack/chirpstack-rest-api:4.6 #should be same version as chirpstack server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
          resources:
            requests:
              cpu: 30m
              memory: 30Mi
            limits:
              memory: 50Mi
          env:
            - name: INSECURE
              value: "0" # indicates chirpstack server gRPC interface is not secured using a TLS cert
            - name: CORS #CORS policy
              value: "*" #allow all origins
      volumes:
        - name: server-config-volume
          configMap:
            name: chirpstack-server-config-cm
            defaultMode: 0644
