apiVersion: apps/v1
kind: Deployment
metadata:
  name: wes-chirpstack-server
spec:
  selector:
    matchLabels:
      app: wes-chirpstack-server
  template:
    metadata:
      labels:
        app: wes-chirpstack-server
    spec:
      priorityClassName: wes-high-priority
      containers:
        - name: wes-chirpstack-server
          image: chirpstack/chirpstack:4.0.2
          command: ["chirpstack"]
          args: ["--config-dir", "/etc/chirpstack-waggle"]
          ports:
            - containerPort: 8080
            - name: metrics
              containerPort: 9100
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
            requests:
              cpu: 50m
              memory: 25Mi
          envFrom:
            - configMapRef:
                name: wes-identity
          env:
            - name: POSTGRESQL_HOST
              value: "wes-chirpstack-postgresql"
            - name: REDIS_HOST
              value: "wes-chirpstack-redis:6379"
            - name: MQTT_BROKER_HOST
              value: "wes-rabbitmq"
            - name: MQTT_BROKER_PORT
              value: "1883"
            - name: MQTT_BROKER_USER
              value: "service"
            - name: MQTT_BROKER_PASSWORD
              value: "service"
            - name: WEB_API_PORT
              value: "8080"
            - name: METRICS_PORT
              value: "9100"
          volumeMounts:
            - name: server-config-volume
              mountPath: /etc/chirpstack-waggle
              readOnly: true
          startupProbe:
            httpGet:
              path: /health
              port: metrics
            initialDelaySeconds: 5
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: metrics
      volumes:
        - name: server-config-volume
          configMap:
            name: chirpstack-server-config-cm
            defaultMode: 0644
