apiVersion: v1
kind: ConfigMap
metadata:
  name: wes-chirpstack-postgresql-configmap
data:
  001-init-chirpstack.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
        create role chirpstack with login password 'chirpstack';
        create database chirpstack with owner chirpstack;
        \c chirpstack
        create extension pg_trgm;
    EOSQL
