apiVersion: apps/v1
kind: Deployment
metadata:
  name: wes-chirpstack-redis
spec:
  selector:
    matchLabels:
      app: wes-chirpstack-redis
  template:
    metadata:
      labels:
        app: wes-chirpstack-redis
    spec:
      priorityClassName: wes-high-priority
      # to ensure we are able to access the PVC
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      containers:
        - name: wes-chirpstack-redis
          image: redis:7.0.4-alpine3.16
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
            requests:
              cpu: 50m
              memory: 25Mi
          envFrom:
            - configMapRef:
                name: wes-identity
          volumeMounts:
            - mountPath: /data
              name: chirpstack-redis-data-volume
          # TODO: liveness probe to ensure its working
      volumes:
        - name: chirpstack-redis-data-volume
          persistentVolumeClaim:
            claimName: wes-chirpstack-redis-data
