#!/bin/bash
set -e

# usage: ./attach-to-dev-notebook vsn
#                                  ^ ex. W030

host="waggle-dev-node-${1}"

echo "Setting up notebook connection to ${1}..."
echo

serviceIP=$(ssh "${host}" sudo kubectl get svc wes-dev-notebook -o jsonpath='{.spec.clusterIP}' 2>/dev/null)

url="http://localhost:8888?token=waggle"

(
    sleep 5
    echo
    echo "Open your browser at: ${url}"
    echo
    (xdg-open "${url}" || open "${url}") &> /dev/null || true
) &

ssh "${host}" -N -L "localhost:8888:${serviceIP}:8888"
